version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/" 
    schedule:
      interval: "weekly"
    reviewers:
      - "vitcosoft"
    assignees:
      - "vitcosoft"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    reviewers:
      - "vitcosoft"
    assignees:
      - "vitcosoft"
